name: create-vectorize-index

on:
  workflow_dispatch: {}

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Vectorize Index
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_VECTORIZE_INDEX: ${{ secrets.CF_VECTORIZE_INDEX }}
        run: |
          npx wrangler@latest vectorize create "$CF_VECTORIZE_INDEX" --dimensions=1024 --metric=cosine
